### PR TITLE
Allow custom functions

### PR DESCRIPTION
**Pull request by huaxk**
Just change `const functions` to  a compile-time sequence variable , you can implement custom function.
so can write code:
```
static:
  functions.add([
    Function(name: "st_asgeojson", arity: 1, typ: dbVarchar),
    Function(name: "json", arity: 1, typ: dbJson),
  ])

let cities = query:
  select cities(id, name, st_asgeomjson(lnglat))

echo cities
```
It is possible to take advantage of  databse built-in function.

### CODE REVIEW

**Comment by Araq** [comment]
Ok, can you add a test case for this please?

**Comment by huaxk** [comment]
It involves database operations, and need to set up a CI system based on github actions.
I can try!

**Comment by Araq** [comment]
Please remove the  tests/tpostgres binary file.

**Comment by huaxk** [comment]
I set up automated tests base on github actions, and tested crud, may be some problems with the delete operation, it raise unhandled exception.
I test some sql function: upper and lower, which functions with only one parameter works ok! but others has problems.

**Comment by Araq** [comment]
Does that mean you want me to review it? Or is this "work in progress"?

**Comment by huaxk** [comment]
Yes, The automated tests has been set up. After you reviewed, then I can test more cases and fix the bug I found.

**Comment by huaxk** [comment]
The current test is mainly for postgresql, and the next step can also be for sqlite.

**Comment by Araq** [comment]
Looks good enough to me.

**Pull request merged**
